// data.jsx — mock content for Laga (Familjen Andersson)
// All Swedish. Exported to window for other babel scripts.

const FAMILY = {
  name: "Familjen Andersson",
  handle: "vadskavi.nu/laga/andersson",
  members: [
    { id: "du",    name: "Du",        full: "Du (Klara)", color: "#c75b39", role: "Ägare" },
    { id: "astrid",name: "Mormor",    full: "Astrid",     color: "#3f7d63", role: "Medlem" },
    { id: "erik",  name: "Pappa",     full: "Erik",       color: "#4a6fa5", role: "Medlem" },
    { id: "sara",  name: "Mamma",     full: "Sara",       color: "#b07d2a", role: "Medlem" },
    { id: "lisa",  name: "Lisa",      full: "Lisa",       color: "#8a5a9e", role: "Medlem" },
    { id: "johan", name: "Johan",     full: "Johan",      color: "#5a8a6e", role: "Inbjuden" },
  ],
};

const M = Object.fromEntries(FAMILY.members.map((m) => [m.id, m]));

const RECIPES = [
  {
    id: "ragu",
    title: "Chef's Ragù Bolognese",
    type: "Recept",
    category: "Huvudrätt",
    tag: "Huvudrätt",
    img: "linear-gradient(135deg,#d98a6a,#c75b39)",
    emoji: "🍝",
    time: "3 tim",
    servings: 6,
    author: "erik",
    cookedBy: [ { id: "astrid", n: 3 }, { id: "erik", n: 1 } ],
    hearts: ["astrid", "sara", "lisa", "du"],
    blurb: "Långkok som blivit familjens söndagsmiddag. Tål att stå.",
    ingredients: [
      "1 kg nötfärs (50% shank, 50% chuck)",
      "400 g fläskbuk, tärnad",
      "100 g pancetta, tärnad",
      "200 g lök, finhackad",
      "150 g morötter, finhackad",
      "150 g selleri, finhackad",
      "1–2 vitlöksklyftor, finhackade",
      "2–3 msk extra virgin olivolja",
      "1–2 msk neutral olja",
      "80 g tomatpuré",
      "400 g passata",
      "200 ml rött vin",
      "500 ml kalvfond",
      "200 ml mjölk",
    ],
    steps: [
      "Bryn färsen i omgångar i den neutrala oljan tills den är riktigt gyllene. Tålamod här ger smaken.",
      "Stek fläskbuk och pancetta tills fettet smält och de fått färg.",
      "Tillsätt lök, morot och selleri. Svetta mjukt i olivoljan, 10 min.",
      "Rör ner tomatpuré och fräs 2 min. Slå på vinet och låt koka in.",
      "Tillsätt passata och fond. Sjud på låg värme minst 2,5 tim.",
      "Rör ner mjölken sista 30 min. Smaka av med salt och svartpeppar.",
    ],
    notes: [
      { id: "erik", text: "Jag tog dubbel vitlök — mycket bättre! Och låt den stå över natten.", date: "för 2 dagar sedan" },
      { id: "astrid", text: "Funkar fint med bara nötfärs om man inte hittar shank.", date: "förra veckan" },
    ],
    comments: [
      { id: "sara", text: "Detta blev söndagsmiddagen, barnen älskade den ❤️", date: "i söndags" },
      { id: "lisa", text: "Gjorde dubbel sats och frös in. Genialt.", date: "för 3 dagar sedan" },
    ],
  },
  {
    id: "pavlova",
    title: "Pavlova med bär",
    type: "Recept",
    category: "Efterrätt",
    tag: "Efterrätt",
    img: "linear-gradient(135deg,#efe7d6,#d8cdb4)",
    emoji: "🍮",
    time: "1 tim 30 min",
    servings: 8,
    author: "sara",
    cookedBy: [ { id: "sara", n: 1 } ],
    hearts: ["astrid", "du"],
    blurb: "Krispig utanpå, seg inuti. Sommarens självklara avslut.",
    ingredients: [
      "4 äggvitor (rumstempererade)",
      "240 g strösocker",
      "1 tsk vitvinsvinäger",
      "1 tsk majsstärkelse",
      "3 dl vispgrädde",
      "Färska bär: hallon, blåbär, jordgubbar",
    ],
    steps: [
      "Vispa äggvitorna till hårt skum. Tillsätt sockret en matsked i taget.",
      "Vänd ner vinäger och majsstärkelse försiktigt.",
      "Forma en rund botten på plåt. Grädda 120°C i 1 tim. Låt svalna i ugnen.",
      "Toppa med vispad grädde och färska bär precis innan servering.",
    ],
    notes: [
      { id: "sara", text: "Vänta med bären till sista stund annars blir botten blöt.", date: "förra månaden" },
    ],
    comments: [
      { id: "du", text: "Bäst med en skvätt citron i grädden!", date: "förra veckan" },
    ],
  },
  {
    id: "kanelbullar",
    title: "Mormors kanelbullar",
    type: "Recept",
    category: "Bakning",
    tag: "Bakning",
    img: "linear-gradient(135deg,#e8c79a,#cf9a5c)",
    emoji: "🥐",
    time: "2 tim",
    servings: 24,
    author: "astrid",
    cookedBy: [ { id: "astrid", n: 5 }, { id: "du", n: 2 }, { id: "lisa", n: 1 } ],
    hearts: ["du", "erik", "sara", "lisa", "johan"],
    blurb: "Originalreceptet. Lika varje gång sedan 1974.",
    ingredients: [
      "50 g jäst",
      "5 dl mjölk",
      "150 g smör",
      "1,5 dl socker",
      "1 tsk salt",
      "2 tsk kardemumma",
      "ca 15 dl vetemjöl",
      "Fyllning: 100 g smör, 1 dl socker, 2 msk kanel",
    ],
    steps: [
      "Smält smöret, häll på mjölken och värm till fingervarmt (37°C).",
      "Lös jästen i degvätskan. Tillsätt socker, salt, kardemumma och mjöl.",
      "Arbeta degen smidig. Låt jäsa under bakduk i 40 min.",
      "Kavla ut, bred på fyllning, rulla och skär bullar.",
      "Jäs 30 min till. Pensla med ägg, strö pärlsocker.",
      "Grädda 225°C i 8–10 min.",
    ],
    notes: [
      { id: "astrid", text: "Hemligheten är att inte ta i för mycket mjöl. Degen ska vara lite kladdig.", date: "för en månad sedan" },
      { id: "du", text: "Jag kör 2,5 tsk kardemumma, gillar det kraftigt.", date: "förra veckan" },
    ],
    comments: [
      { id: "johan", text: "Dessa är hela min barndom 🥹", date: "för 2 dagar sedan" },
    ],
  },
  {
    id: "kottbullar",
    title: "Köttbullar & gräddsås",
    type: "Recept",
    category: "Huvudrätt",
    tag: "Huvudrätt",
    img: null,
    emoji: "🍽️",
    time: "45 min",
    servings: 4,
    author: "du",
    cookedBy: [ { id: "du", n: 4 }, { id: "erik", n: 2 } ],
    hearts: ["astrid", "sara"],
    blurb: "Vardagsräddaren. Finns alltid i frysen.",
    ingredients: [
      "500 g blandfärs",
      "1 dl ströbröd",
      "1 dl mjölk",
      "1 ägg",
      "1/2 gul lök, riven",
      "Smör till stekning",
      "Sås: 2 dl grädde, 1 dl vatten, soja, kalvfond",
    ],
    steps: [
      "Blötlägg ströbröd i mjölk. Blanda med färs, ägg och lök.",
      "Rulla bollar, stek gyllene i smör.",
      "Koka ihop såsen i pannan, smaka av med soja.",
    ],
    notes: [],
    comments: [],
  },
  {
    id: "kladdkaka",
    title: "Kladdkaka",
    type: "Recept",
    category: "Bakning",
    tag: "Efterrätt",
    img: "linear-gradient(135deg,#7a5440,#4a3024)",
    emoji: "🍫",
    time: "30 min",
    servings: 10,
    author: "lisa",
    cookedBy: [ { id: "lisa", n: 3 } ],
    hearts: ["du", "johan", "erik"],
    blurb: "Klibbig mitt, tunt knäck på toppen.",
    ingredients: ["2 ägg", "2,5 dl socker", "3 msk kakao", "1,5 dl mjöl", "100 g smör", "1 tsk vaniljsocker"],
    steps: [
      "Smält smöret. Vispa ägg och socker pösigt.",
      "Blanda i kakao, mjöl och vaniljsocker, sedan smöret.",
      "Grädda 175°C i 15 min — mitten ska vara kladdig.",
    ],
    notes: [ { id: "lisa", text: "Ta ut den när den ser ogräddad ut, den stelnar.", date: "förra veckan" } ],
    comments: [],
  },
  {
    id: "raksmorgas",
    title: "Räksmörgås",
    type: "Recept",
    category: "Förrätt",
    tag: "Förrätt",
    img: "linear-gradient(135deg,#f0b6a0,#e0846a)",
    emoji: "🦐",
    time: "15 min",
    servings: 2,
    author: "erik",
    cookedBy: [ { id: "erik", n: 1 } ],
    hearts: ["du"],
    blurb: "Lyxig lunch på en kvart.",
    ingredients: ["Surdegsbröd", "200 g handskalade räkor", "Majonnäs", "Ägg", "Sallad, dill, citron"],
    steps: ["Bred majonnäs på rostat bröd.", "Lägg sallad, ägg och räkor.", "Toppa med dill och citron."],
    notes: [],
    comments: [],
  },
  {
    id: "glogg",
    title: "Familjens glögg",
    type: "Recept",
    category: "Dryck",
    tag: "Dryck",
    img: "linear-gradient(135deg,#9e3b3b,#6e2424)",
    emoji: "🍷",
    time: "20 min + dygn",
    servings: 12,
    author: "astrid",
    cookedBy: [ { id: "astrid", n: 2 }, { id: "sara", n: 1 } ],
    hearts: ["erik", "du", "lisa"],
    blurb: "Kryddas dagen innan. Julens doft.",
    ingredients: ["1 flaska rött vin", "2 dl portvin", "Kanelstång, kardemumma, nejlika", "Skal av 1 apelsin", "Socker efter smak", "Russin & mandel"],
    steps: ["Värm vin med kryddor och apelsinskal, men koka ej.", "Låt dra över natten.", "Värm, sila, servera med russin och mandel."],
    notes: [],
    comments: [],
  },
  {
    id: "ortforvaring",
    title: "Håll örter färska längre",
    type: "Tips",
    category: "Förvaring",
    tag: "Förvaring",
    img: null,
    emoji: "🌿",
    time: null,
    servings: null,
    author: "sara",
    cookedBy: [],
    hearts: ["du", "astrid", "lisa"],
    blurb: "Ett litet knep som räddar persiljan.",
    ingredients: null,
    steps: [
      "Skär av stjälkändarna på örterna.",
      "Ställ dem som en bukett i ett glas med lite vatten.",
      "Sätt en plastpåse löst över och ställ i kylen. Håller i 2 veckor.",
    ],
    notes: [ { id: "astrid", text: "Funkar för basilika också, men den vill stå i rumstemperatur.", date: "förra månaden" } ],
    comments: [],
  },
];

const R = Object.fromEntries(RECIPES.map((r) => [r.id, r]));

// Activity feed for family view
const ACTIVITY = [
  { who: "astrid", action: "lagade", target: "ragu", when: "Idag 18:20" },
  { who: "johan", action: "kommenterade", target: "kanelbullar", when: "Idag 14:05" },
  { who: "lisa",  action: "lade till", target: "kladdkaka", when: "Igår" },
  { who: "sara",  action: "gillade", target: "ragu", when: "Igår" },
  { who: "du",    action: "lagade", target: "kanelbullar", when: "2 dagar sedan" },
  { who: "erik",  action: "lade till", target: "raksmorgas", when: "3 dagar sedan" },
];

const CATEGORIES = ["Alla", "Bakning", "Dryck", "Efterrätt", "Frukost", "Förrätt", "Förvaring"];

Object.assign(window, { FAMILY, M, RECIPES, R, ACTIVITY, CATEGORIES });
